GET http://localhost:8000/todos

###

 POST http://localhost:8000/todo/new
 Content-Type: application/json

 {
  "text": "Banana"
 }

### 
 
 DELETE http://localhost:8000/todo/delete/64c82ae7fa3488fdfc1d4c45

###

PUT http://localhost:8000/todo/complete/64c82a71fa3488fdfc1d4c3f

###

 POST http://localhost:8000/todo/new
 Content-Type: application/json

 {
  "text": "Coding like a PRO!!"
 }

###

GET http://localhost:8000/todo/complete/64ca370c122070e84347a443
